# Generated by Django 2.2.2 on 2020-12-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not accepted', 'Not Accepted'), ('pending', 'Pending'), ('on delivery', 'On delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not accepted', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='TruckShare.Transporter'),
        ),
    ]
