# Generated by Django 2.2.2 on 2020-12-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0002_auto_20201208_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='goodsType',
            new_name='goodsTypes',
        ),
    ]
