# Generated by Django 2.2.2 on 2020-12-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0003_auto_20201208_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
