# Generated by Django 2.2.2 on 2020-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0004_auto_20201209_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(choices=[('SMT1', 'Small Moving Truck-1'), ('SMT2', 'Small Moving Truck-2'), ('LMT1', 'Large Moving Truck-1'), ('LMT2', 'Large Moving Truck-2')], default='SMT1', max_length=4),
        ),
    ]
