# Generated by Django 2.2.2 on 2020-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0005_auto_20201209_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='type',
            new_name='truckType',
        ),
        migrations.AddField(
            model_name='transporter',
            name='trucksOwned',
            field=models.IntegerField(default=0),
        ),
    ]
