# Generated by Django 2.2.2 on 2020-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0006_auto_20201209_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='trucks',
            field=models.ManyToManyField(related_name='transporters', to='TruckShare.Truck'),
        ),
    ]
