# Generated by Django 2.2.2 on 2020-12-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0008_truck_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='trucks',
        ),
        migrations.AddField(
            model_name='transporter',
            name='trucks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TruckShare.Truck'),
        ),
    ]
