# Generated by Django 2.2.2 on 2020-12-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0009_auto_20201209_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='trucks',
        ),
        migrations.AddField(
            model_name='truck',
            name='parkedAt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkedTrucks', to='TruckShare.Transporter'),
        ),
    ]
