# Generated by Django 2.2.2 on 2020-12-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0010_auto_20201209_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownedTrucks', to='TruckShare.Transporter'),
        ),
    ]
