# Generated by Django 2.2.2 on 2020-12-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0011_auto_20201209_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter',
            old_name='trucksOwned',
            new_name='numTrucksOwned',
        ),
    ]
