# Generated by Django 2.2.2 on 2020-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0012_auto_20201210_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ManyToManyField(related_name='orders', to='TruckShare.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on delivery', 'On delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not accepted', max_length=12),
        ),
    ]
