# Generated by Django 2.2.2 on 2020-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0013_auto_20201212_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='volumeFilled',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='weightFilled',
            field=models.IntegerField(null=True),
        ),
    ]
