# Generated by Django 2.2.2 on 2020-12-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0014_auto_20201212_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='departure',
        ),
        migrations.CreateModel(
            name='OrderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TruckShare.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ManyToManyField(related_name='dateDeliveries', to='TruckShare.OrderDate'),
        ),
        migrations.AddField(
            model_name='order',
            name='departure',
            field=models.ManyToManyField(related_name='dateDepartures', to='TruckShare.OrderDate'),
        ),
    ]
