# Generated by Django 2.2.2 on 2020-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0015_auto_20201212_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on delivery', 'On delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
