# Generated by Django 2.2.2 on 2020-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0016_auto_20201212_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TimeFlexibility',
        ),
    ]
