# Generated by Django 2.2.2 on 2020-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckShare', '0018_auto_20201213_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not accepted', 'Not Accpeted'), ('pending', 'Pending'), ('on delivery', 'On delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='not accepted', max_length=12),
        ),
    ]
